defaults: &defaults
  app_name: "curate"
  

development:
  <<: *defaults
  domain: "http://localhost:3000/"

test:
  <<: *defaults

production:
  <<: *defaults
  domain: "http://fathomless-harbor-6451.herokuapp.com/"