defaults: &defaults
  app_name: "curate"
  embedly_key: "77b9e769557a490e9e2ef087981131c3"

development:
  <<: *defaults
  domain: "http://localhost:3000/"

test:
  <<: *defaults

production:
  <<: *defaults
  domain: "http://fathomless-harbor-6451.herokuapp.com/"