# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7de521d95b6431938faa6622382ee1b9c1c658dcc2a8cf8532905e51426bb6bddf73a7188f7163d00b244beb93f8991fbaf03d49e9c548eed0636dcf0e86bb20

test:
  secret_key_base: d260713cfc0079cddb22c8ea19c4323bf8a9582de7dff724dd1247289829c453c32ec55ec3e8d6f3b00c9f003b03183fec3704df9f28152ecce85f61f70f2390

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
